[package]
name = "sswm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
confy = "0.5.1"
directories = "5.0.1"
penrose = "0.3.3"
serde = { version = "1.0.181", features = ["derive"] }
serde_json = "1.0.104"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
